"""auto update

Revision ID: 72a3b34d29e7
Revises: 2e2a241c1354
Create Date: 2026-09-29 06:38:27.232715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a3b34d29e7'
down_revision: Union[str, Sequence[str], None] = '2e2a241c1354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('share_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'share_token')
    # ### end Alembic commands ###